version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      allow:
          - dependency-name: "@apst/biome"
          - dependency-name: "@apst/tsconfig"
          - dependency-name: "@biomejs/biome"
          - dependency-name: "@hono/node-server"
          - dependency-name: "@hono/vite-build"
          - dependency-name: "@hono/vite-dev-server"
          - dependency-name: "@types/node"
          - dependency-name: "tsup"
          - dependency-name: "typedoc"
          - dependency-name: "typedoc-plugin-markdown"
          - dependency-name: "typescript"
          - dependency-name: "vite"
          - dependency-name: "vite-tsconfig-paths"
          - dependency-name: "vitest"
